server:
  port: 8888
  servlet:
    context-path: /uid
    encoding:
      force: true
      charset: utf-8
      enabled: true

spring:
  application:
    name: uid-generator
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/micro-uid-generator?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: root
    druid:
      # 初始连接数
      initial-size: 2
      # 最小连接池数量
      min-idle: 0
      # 最大连接池数量
      max-active: 2
      # 配置获取连接等待超时的时间
      max-wait: 5000
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      # 配置检测连接是否有效
      validation-query: select 1 from dual
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 30000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 60000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      max-evictable-idle-time-millis: 900000
      log-abandoned: true
      remove-abandoned: true
      remove-abandoned-timeout: 120
      filters: stat

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.baidu.fsg.uid.worker.entity
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  global-config:
    banner: true

uid-generator:
  token: e296e6cc98d84c40b2d9f7b86287c6e6
  # 对于并发数要求不高、期望长期使用的应用, 可增加timeBits位数, 减少seqBits位数.
  # 例如节点采取用完即弃的WorkerIdAssigner策略, 重启频率为12次/天, 那么配置成{"workerBits":23,"timeBits":31,"seqBits":9}时,
  # 可支持28个节点以整体并发量14400 UID/s的速度持续运行68年.

  # 对于节点重启频率频繁、期望长期使用的应用, 可增加workerBits和timeBits位数, 减少seqBits位数.
  # 例如节点采取用完即弃的WorkerIdAssigner策略, 重启频率为24*12次/天, 那么配置成{"workerBits":27,"timeBits":30,"seqBits":6}时,
  # 可支持37个节点以整体并发量2400 UID/s的速度持续运行34年.
  timeBits: 29
  workerBits: 21
  seqBits: 13
  epochStr: 2016-09-20
  # RingBuffer size扩容参数, 可提高UID生成的吞吐量.
  # 默认:3， 原bufferSize=8192, 扩容后bufferSize= 8192 << 3 = 65536
  boostPower: 3
  # 指定何时向RingBuffer中填充UID, 取值为百分比(0, 100), 默认为50
  # 举例: bufferSize=1024, paddingFactor=50 -> threshold=1024 * 50 / 100 = 512.
  # 当环上可用UID数量 < 512时, 将自动对RingBuffer进行填充补全
  paddingFactor: 30
  # 另外一种RingBuffer填充时机, 在Schedule线程中, 周期性检查填充
  # 默认:不配置此项, 即不实用Schedule线程. 如需使用, 请指定Schedule线程时间间隔, 单位:秒
  scheduleInterval: 60